# Generated by Django 3.1 on 2020-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='iscustom',
            field=models.BooleanField(default=True),
        ),
    ]
